name: Test nixvim flake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - run: nix flake check
      - run: nix build .#nixvim

